services:
  - type: web
    name: beehouse
    approx: python
    buildCommand: ./build.sh
    startCommand: python -m gunicorn BeeHouse.asgi:application
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: behoouse_tv2
          property: connectionstring
      - key: PYTHON_VERSION

        value: 3.11.0


