databases:
  - name: behoouse_tv2
    plan: free
    databaseName: behoouse_tv2
    user: behoouse_tv2_user

services:
  - type: web
    plan: free
    name: Beehouse
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn BeeHouse.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT' 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: behoouse_tv2
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4






