databases:
  - name: behoouse_tv2
    plan: free
    databaseName: behoouse_tv2
    user: behoouse_tv2_user

services:
  - type: web
    plan: free
    name: Beehouse
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'gunicorn BeeHouse.asgi:application' 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: behoouse_tv2
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4





